export const mockData: { count: number; results: any[] } = {
  count: 60,
  results: [
    {
      id: '1',
      firstName: 'Darya',
      lastName: 'Tema',
      github: 'besovadevka',
      telegram: 'besova_devka',
      discord: 'Darya',
      score: 80,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar.png',
      email: 'timaph@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '2',
      firstName: 'Sergei',
      lastName: 'Smth',
      github: 'github',
      telegram: 'tg',
      discord: 'Sergei',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar2.png',
      email: 'sergei@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '3',
      firstName: 'Sasha',
      lastName: 'Malagor',
      github: 'Malagor',
      telegram: 'malagor',
      discord: 'Malagor',
      score: 20,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar3.png',
      email: 'malagor@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '4',
      firstName: 'Olga',
      lastName: 'Smth',
      github: 'gryzun33',
      telegram: 'gryzun33',
      discord: 'gryzun33',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar5.png',
      email: 'gryzun33@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '5',
      firstName: 'Andrei',
      lastName: 'lastName',
      github: 'veryLongGithub',
      telegram: 'veryLongTelegram',
      discord: 'Andrei',
      score: 114,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar7.png',
      email: 'andrei@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '1',
      firstName: 'Darya',
      lastName: 'Tema',
      github: 'besovadevka',
      telegram: 'besova_devka',
      discord: 'Darya',
      score: 80,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar.png',
      email: 'timaph@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '2',
      firstName: 'Sergei',
      lastName: 'Smth',
      github: 'github',
      telegram: 'tg',
      discord: 'Sergei',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar2.png',
      email: 'sergei@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '3',
      firstName: 'Sasha',
      lastName: 'Malagor',
      github: 'Malagor',
      telegram: 'malagor',
      discord: 'Malagor',
      score: 20,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar3.png',
      email: 'malagor@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '4',
      firstName: 'Olga',
      lastName: 'Smth',
      github: 'gryzun33',
      telegram: 'gryzun33',
      discord: 'gryzun33',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar5.png',
      email: 'gryzun33@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '5',
      firstName: 'Andrei',
      lastName: 'lastName',
      github: 'veryLongGithub',
      telegram: 'veryLongTelegram',
      discord: 'Andrei',
      score: 114,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar7.png',
      email: 'andrei@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '1',
      firstName: 'Darya',
      lastName: 'Tema',
      github: 'besovadevka',
      telegram: 'besova_devka',
      discord: 'Darya',
      score: 80,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar.png',
      email: 'timaph@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '2',
      firstName: 'Sergei',
      lastName: 'Smth',
      github: 'github',
      telegram: 'tg',
      discord: 'Sergei',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar2.png',
      email: 'sergei@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '3',
      firstName: 'Sasha',
      lastName: 'Malagor',
      github: 'Malagor',
      telegram: 'malagor',
      discord: 'Malagor',
      score: 20,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar3.png',
      email: 'malagor@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '4',
      firstName: 'Olga',
      lastName: 'Smth',
      github: 'gryzun33',
      telegram: 'gryzun33',
      discord: 'gryzun33',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar5.png',
      email: 'gryzun33@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '5',
      firstName: 'Andrei',
      lastName: 'lastName',
      github: 'veryLongGithub',
      telegram: 'veryLongTelegram',
      discord: 'Andrei',
      score: 114,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar7.png',
      email: 'andrei@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '1',
      firstName: 'Darya',
      lastName: 'Tema',
      github: 'besovadevka',
      telegram: 'besova_devka',
      discord: 'Darya',
      score: 80,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar.png',
      email: 'timaph@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '2',
      firstName: 'Sergei',
      lastName: 'Smth',
      github: 'github',
      telegram: 'tg',
      discord: 'Sergei',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar2.png',
      email: 'sergei@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '3',
      firstName: 'Sasha',
      lastName: 'Malagor',
      github: 'Malagor',
      telegram: 'malagor',
      discord: 'Malagor',
      score: 20,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar3.png',
      email: 'malagor@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '4',
      firstName: 'Olga',
      lastName: 'Smth',
      github: 'gryzun33',
      telegram: 'gryzun33',
      discord: 'gryzun33',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar5.png',
      email: 'gryzun33@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '5',
      firstName: 'Andrei',
      lastName: 'lastName',
      github: 'veryLongGithub',
      telegram: 'veryLongTelegram',
      discord: 'Andrei',
      score: 114,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar7.png',
      email: 'andrei@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '1',
      firstName: 'Darya',
      lastName: 'Tema',
      github: 'besovadevka',
      telegram: 'besova_devka',
      discord: 'Darya',
      score: 80,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar.png',
      email: 'timaph@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '2',
      firstName: 'Sergei',
      lastName: 'Smth',
      github: 'github',
      telegram: 'tg',
      discord: 'Sergei',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar2.png',
      email: 'sergei@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '3',
      firstName: 'Sasha',
      lastName: 'Malagor',
      github: 'Malagor',
      telegram: 'malagor',
      discord: 'Malagor',
      score: 20,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar3.png',
      email: 'malagor@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '4',
      firstName: 'Olga',
      lastName: 'Smth',
      github: 'gryzun33',
      telegram: 'gryzun33',
      discord: 'gryzun33',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar5.png',
      email: 'gryzun33@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '5',
      firstName: 'Andrei',
      lastName: 'lastName',
      github: 'veryLongGithub',
      telegram: 'veryLongTelegram',
      discord: 'Andrei',
      score: 114,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar7.png',
      email: 'andrei@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '1',
      firstName: 'Darya',
      lastName: 'Tema',
      github: 'besovadevka',
      telegram: 'besova_devka',
      discord: 'Darya',
      score: 80,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar.png',
      email: 'timaph@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '2',
      firstName: 'Sergei',
      lastName: 'Smth',
      github: 'github',
      telegram: 'tg',
      discord: 'Sergei',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar2.png',
      email: 'sergei@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '3',
      firstName: 'Sasha',
      lastName: 'Malagor',
      github: 'Malagor',
      telegram: 'malagor',
      discord: 'Malagor',
      score: 20,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar3.png',
      email: 'malagor@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '4',
      firstName: 'Olga',
      lastName: 'Smth',
      github: 'gryzun33',
      telegram: 'gryzun33',
      discord: 'gryzun33',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar5.png',
      email: 'gryzun33@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '5',
      firstName: 'Andrei',
      lastName: 'lastName',
      github: 'veryLongGithub',
      telegram: 'veryLongTelegram',
      discord: 'Andrei',
      score: 114,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar7.png',
      email: 'andrei@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '1',
      firstName: 'Darya',
      lastName: 'Tema',
      github: 'besovadevka',
      telegram: 'besova_devka',
      discord: 'Darya',
      score: 80,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar.png',
      email: 'timaph@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '2',
      firstName: 'Sergei',
      lastName: 'Smth',
      github: 'github',
      telegram: 'tg',
      discord: 'Sergei',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar2.png',
      email: 'sergei@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '3',
      firstName: 'Sasha',
      lastName: 'Malagor',
      github: 'Malagor',
      telegram: 'malagor',
      discord: 'Malagor',
      score: 20,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar3.png',
      email: 'malagor@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '4',
      firstName: 'Olga',
      lastName: 'Smth',
      github: 'gryzun33',
      telegram: 'gryzun33',
      discord: 'gryzun33',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar5.png',
      email: 'gryzun33@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '5',
      firstName: 'Andrei',
      lastName: 'lastName',
      github: 'veryLongGithub',
      telegram: 'veryLongTelegram',
      discord: 'Andrei',
      score: 114,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar7.png',
      email: 'andrei@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '1',
      firstName: 'Darya',
      lastName: 'Tema',
      github: 'besovadevka',
      telegram: 'besova_devka',
      discord: 'Darya',
      score: 80,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar.png',
      email: 'timaph@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '2',
      firstName: 'Sergei',
      lastName: 'Smth',
      github: 'github',
      telegram: 'tg',
      discord: 'Sergei',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar2.png',
      email: 'sergei@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '3',
      firstName: 'Sasha',
      lastName: 'Malagor',
      github: 'Malagor',
      telegram: 'malagor',
      discord: 'Malagor',
      score: 20,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar3.png',
      email: 'malagor@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '4',
      firstName: 'Olga',
      lastName: 'Smth',
      github: 'gryzun33',
      telegram: 'gryzun33',
      discord: 'gryzun33',
      score: 14,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar5.png',
      email: 'gryzun33@mail.ru',
      isAdmin: false,
      courseIds: ['JS'],
      teamIds: ['second'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
    {
      id: '5',
      firstName: 'Andrei',
      lastName: 'lastName',
      github: 'veryLongGithub',
      telegram: 'veryLongTelegram',
      discord: 'Andrei',
      score: 114,
      country: 'Belarus',
      city: 'Minsk',
      avatar: 'someAvatar7.png',
      email: 'andrei@mail.ru',
      isAdmin: false,
      courseIds: ['JS', 'React'],
      teamIds: ['first', 'third'],
      courses: [
        {
          id: 'JS',
          name: 'FRONT END',
          teamIds: ['first', 'second'],
          userIds: ['1', '2', '4', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
        {
          id: 'React',
          name: 'REACT',
          teamIds: ['third'],
          userIds: ['1', '3', '5'],
          teams: [{}, {}],
          users: [{}, {}],
        },
      ],
      teams: [
        {
          id: 'first',
          number: 4,
          password: '1234',
          courseId: 'JS',
          socialLink: '@teamFirst',
          memberIds: ['1', '2', '4', '5'],
          course: {},
          members: [{}, {}],
        },
        {
          id: 'third',
          number: 3,
          password: '1234',
          courseId: 'React',
          socialLink: '@teamFThird',
          memberIds: ['1', '4', '5'],
          course: {},
          members: [{}, {}],
        },
      ],
    },
  ],
};
