export const WHITE_COLOR = '#FFFFFF';
export const BACKGROUND_COLOR = '#F2F8FD';
export const MAIN1_COLOR = '#6550F6'; // violet
export const MAIN1_DARK_COLOR = '#5039EF'; // dark violet
export const MAIN2_COLOR = '#FA6678'; // red
export const MAIN2_LIGHT_COLOR = '#FE7888'; // light red
export const LIGHT_TEXT_COLOR = '#7E96C2';
export const DARK_TEXT_COLOR = '#363D48';
export const DASHBOARD_HEADER_BACKGROUND_COLOR = '#E1EEFA';
